trigger:
- main  # Ajusta esto según la rama que deseas que dispare el pipeline

jobs:
- job: AgentJob
  pool:
    name: 'cicd denodo pipeline'  # Nombre de tu agente local
  steps:
  - checkout: self
  - script: cat example/base64revision.py
    displayName: 'Print base64revision.py'
