trigger:
- main

resources:
  repositories:
  - repository: MyAzureRepo
    type: git
    name: example/example
    ref: refs/heads/main

pool:
  vmImage: 'windows-latest'

jobs:
- job: HostedAgentJob
  steps:
  - checkout: MyAzureRepo
  - script: type base64revision.py
    displayName: 'Print base64revision.py'
  - script: echo "Tarea hecha"
    displayName: 'Ejecutar Script'