trigger:
- main  # Ajusta esto según la rama que deseas que dispare el pipeline

pool:
  vmImage: 'windows-latest'  # O usa 'ubuntu-latest', 'macOS-latest', según tus necesidades

jobs:
- job: HostedAgentJob
  steps:
  - checkout: self
  - script: type base64revision.py
  displayName: 'Print base64revision.py'